modules_cc =\
  Modules/MGauge/Load.cc \
  Modules/MGauge/Unit.cc \
  Modules/MGauge/Random.cc

modules_hpp =\
  Modules/Quark.hpp \
  Modules/MGauge/Unit.hpp \
  Modules/MGauge/Load.hpp \
  Modules/MGauge/Random.hpp \
  Modules/MAction/Wilson.hpp \
  Modules/MAction/DWF.hpp \
  Modules/MContraction/Baryon.hpp \
  Modules/MContraction/TwoPion.hpp \
  Modules/MContraction/Meson.hpp \
  Modules/MSource/SeqGamma.hpp \
  Modules/MSource/Point.hpp \
  Modules/MSource/Z2.hpp \
  Modules/MSolver/RBPrecCG.hpp

